# Generated by Django 4.2 on 2024-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJuridica', '0002_cliente_datosdecontacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_de_caso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(max_length=8),
        ),
    ]
